# Dockerfile for RNAseq Container

FROM ubuntu:18.04

# set a directory for the app
WORKDIR /home/ec2-user/docker

# basic configuration
RUN apt-get update \
        && apt-get install -y \
                ed \
                less \
                locales \
                gzip \
                unzip \
		        pigz \
                perl \
                wget \
                python3.8


## Configure default locale, see https://github.com/rocker-org/rocker/issues/19
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
        && locale-gen en_US.utf8 \
        && /usr/sbin/update-locale LANG=en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive


# conda setup
ENV MINI_VERSION 4.7.12.1
ENV PATH /opt/conda/bin:$PATH


RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${MINI_VERSION}-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc


COPY conda_dependencies.yml .
RUN conda env create -f conda_dependencies.yml


RUN echo "source activate rnaseq-nf" > ~/.bashrc
ENV PATH /opt/conda/envs/rnaseq-nf/bin:$PATH


# clean conda environment
RUN conda clean --yes --all
